fix(TDQ-21427): use download colt-1.2.0.jar (#1211)
* Revert "fix(TDQ-21427): fix NoClassDefFoundError (#1209)"

This reverts commit 6d8991494708083cd0d751f21915edd68623a36a.

* fix(TDQ-21427): use download colt-1.2.0.jar